### PR TITLE
Preprocessing functions: 2 new functions!

### PR DESCRIPTION
**Pull request by dialectique**
The package is updated.

deep_painting_app.explore_data:
display_paintings_and_classes
random_painting (new!)
number_img_per_class (new!)

deep_painting_app.data_processing librairy:
load_and_divide_dataset
classes_names_to_dict
give_class_name

Thank you for your check!
I will merge with the main branch after your approval!

### CODE REVIEW

**Review by kdurak — APPROVED** [review]
Thank you!

**Review by kdurak — APPROVED** [review]
Thank you!

**Review by deepanjalisingh — APPROVED** [review]
looks good

**Review by TokyoFixed — APPROVED** [review]
Looks good, I approve, thanks!

**Review by TokyoFixed — COMMENTED** [review]
Changes look good to me!

**Review by deepanjalisingh — COMMENTED** [review]
looks good

**Pull request merged**
